import ImageOne from './ImageSource/1.jpg';

export const classListData = [
{
  id: 1,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: `url(${ImageOne})`,
},
{
id: 2,
category: 'Hand Made',
title: 'Hand made necklaces, Jewelley class.',
location: 'Busan, Korea',
tag: '#hand made#jewelley#necklaces',
copyright: 'Photo by Jose Maria Garcia on Unsplash',
image: './ImageSource/1.jpg',
},
{
id: 3,
category: 'Hand Made',
title: 'Hand made necklaces, Jewelley class.',
location: 'Busan, Korea',
tag: '#hand made#jewelley#necklaces',
copyright: 'Photo by Jose Maria Garcia on Unsplash',
image: './ImageSource/1.jpg',
},
{
  id: 4,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},
{
  id: 5,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},

{
  id: 6,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},
{
  id: 7,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},
{
  id: 8,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},
{
  id: 9,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},
{
  id: 10,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},
{
  id: 11,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},
{
  id: 12,
  category: 'Hand Made',
  title: 'Hand made necklaces, Jewelley class.',
  location: 'Busan, Korea',
  tag: '#hand made#jewelley#necklaces',
  copyright: 'Photo by Jose Maria Garcia on Unsplash',
  image: './ImageSource/1.jpg',
},
    
]